from datetime import date
from django.core.management.base import BaseCommand
from core.models import Servicio, Habilidad, Proyecto


class Command(BaseCommand):
    help = 'Carga datos iniciales de servicios, habilidades y proyectos'

    def handle(self, *args, **options):
        # Servicios
        servicios = [
            {'icono': '📱', 'titulo': 'Gestión de Redes Sociales', 'descripcion': 'Estrategia, calendario editorial, diseño y publicación en Instagram, TikTok y Facebook. Reportes mensuales.', 'orden': 1},
            {'icono': '🔍', 'titulo': 'SEO & Email Marketing', 'descripcion': 'Optimización de contenido, palabras clave, redacción SEO y campañas de email orientadas a conversión.', 'orden': 2},
            {'icono': '🎯', 'titulo': 'Campañas Meta Ads', 'descripcion': 'Creación y gestión de campañas en Facebook e Instagram: segmentación, creativos, A/B testing y optimización.', 'orden': 3},
            {'icono': '🎨', 'titulo': 'Diseño de Contenido', 'descripcion': 'Posts, Reels, Stories y carruseles con identidad de marca. Canva avanzado + CapCut.', 'orden': 4},
            {'icono': '📊', 'titulo': 'Análisis & Reportes', 'descripcion': 'KPIs, métricas de desempeño y reportes ejecutivos con insights accionables.', 'orden': 5},
            {'icono': '🗂️', 'titulo': 'Coordinación de Contenido', 'descripcion': 'Gestión del flujo editorial completo: briefs, control de entregables, consistencia de marca.', 'orden': 6},
        ]
        for s in servicios:
            Servicio.objects.update_or_create(titulo=s['titulo'], defaults=s)
        self.stdout.write(self.style.SUCCESS(f'{len(servicios)} servicios cargados'))

        # Habilidades
        habilidades = [
            ('Planificacion trimestral/mensual', 'Estrategia', 1),
            ('Calendarios editoriales', 'Estrategia', 2),
            ('Ecosistema digital', 'Estrategia', 3),
            ('Crecimiento organico', 'Estrategia', 4),
            ('SEO', 'SEO & Ads', 1),
            ('Email Marketing', 'SEO & Ads', 2),
            ('Meta Ads', 'SEO & Ads', 3),
            ('Funnels', 'SEO & Ads', 4),
            ('Copywriting', 'SEO & Ads', 5),
            ('Canva', 'Herramientas', 1),
            ('CapCut', 'Herramientas', 2),
            ('Asana', 'Herramientas', 3),
            ('Slack', 'Herramientas', 4),
            ('Google Workspace', 'Herramientas', 5),
            ('ChatGPT / Gemini', 'Herramientas', 6),
            ('Google Analytics', 'Analytics', 1),
            ('Meta Business Suite', 'Analytics', 2),
            ('KPIs', 'Analytics', 3),
            ('Reportes', 'Analytics', 4),
        ]
        for nombre, cat, orden in habilidades:
            Habilidad.objects.update_or_create(nombre=nombre, defaults={'categoria': cat, 'orden': orden})
        self.stdout.write(self.style.SUCCESS(f'{len(habilidades)} habilidades cargadas'))

        # Proyectos
        proyectos = [
            {
                'titulo': 'Post Instagram - Servicio de Spa',
                'slug': 'dogo-armani-post-turquesa',
                'descripcion': 'Post promocional para Dogo Armani destacando el servicio de spa y peluqueria canina. Diseno con identidad de marca en turquesa y amarillo.',
                'descripcion_larga': 'Pieza grafica disenada en Canva para el feed de Instagram de Dogo Armani. El post comunica el servicio principal del petshop con un mensaje emocional: "La felicidad de tu peludo comienza aqui". Incluye datos de contacto y ubicacion para facilitar la conversion.',
                'imagen_estatica': 'img/dogo_post_turquesa.jpeg',
                'categoria': 'Instagram',
                'tags': 'Canva, Diseno de Post, Copywriting, Redes Sociales',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 11, 15),
                'destacado': True,
                'orden': 1,
            },
            {
                'titulo': 'Post Instagram - Servicios del Petshop',
                'slug': 'dogo-armani-post-purpura',
                'descripcion': 'Post informativo mostrando los 3 servicios principales de Dogo Armani: peluqueria canina, accesorios y comida organica.',
                'descripcion_larga': 'Diseno en la paleta corporativa purpura y amarillo de Dogo Armani. La pieza destaca los servicios clave con iconografia clara y un llamado a la accion hacia el perfil de Instagram @dogoarmani.',
                'imagen_estatica': 'img/dogo_post_purpura.jpeg',
                'categoria': 'Instagram',
                'tags': 'Canva, Branding, Diseno de Post, Estrategia',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 10, 20),
                'destacado': False,
                'orden': 2,
            },
            {
                'titulo': 'Calendario Editorial - Enero',
                'slug': 'dogo-armani-calendario-enero',
                'descripcion': 'Calendario editorial del mes de enero para Dogo Armani. Planificacion de contenido mensual con identidad visual de marca.',
                'descripcion_larga': 'Calendario disenado como parte de la estrategia de contenido mensual. Cada mes tiene una mascota protagonista y mantiene la coherencia visual de Dogo Armani.',
                'imagen_estatica': 'img/dogo_calendario_enero.jpeg',
                'categoria': 'Estrategia',
                'tags': 'Calendario Editorial, Planificacion, Canva, Estrategia de Contenido',
                'cliente': 'Dogo Armani',
                'fecha': date(2026, 1, 1),
                'destacado': False,
                'orden': 3,
            },
            {
                'titulo': 'Calendario Editorial - Febrero',
                'slug': 'dogo-armani-calendario-febrero',
                'descripcion': 'Calendario editorial del mes de febrero para Dogo Armani con tematica de mascotas.',
                'imagen_estatica': 'img/dogo_calendario_febrero.jpeg',
                'categoria': 'Estrategia',
                'tags': 'Calendario Editorial, Planificacion, Canva',
                'cliente': 'Dogo Armani',
                'fecha': date(2026, 2, 1),
                'destacado': False,
                'orden': 4,
            },
            {
                'titulo': 'Etiquetas Navidenas - Dogo Armani',
                'slug': 'dogo-armani-etiquetas-navidad',
                'descripcion': 'Diseno de etiquetas navidenas para productos de Dogo Armani. Material impreso con identidad de marca para la temporada festiva.',
                'descripcion_larga': 'Coleccion de 6 etiquetas navidenas disenadas para acompanar los productos y regalos de Dogo Armani durante la temporada de fiestas. Frente con ilustraciones doradas sobre fondo azul marino, y reverso con mensaje personalizado.',
                'imagen_estatica': 'img/dogo_etiquetas_frente.jpeg',
                'imagen_extra_estatica': 'img/dogo_etiquetas_reverso.jpeg',
                'categoria': 'Diseno',
                'tags': 'Canva, Material Impreso, Branding, Diseno Grafico',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 12, 10),
                'destacado': True,
                'orden': 5,
            },
            {
                'titulo': 'Gestion de Instagram - Dogo Armani',
                'slug': 'dogo-armani-instagram',
                'descripcion': 'Gestion integral del perfil de Instagram @dogoarmani: estrategia de contenido, diseno de posts, copywriting y crecimiento organico.',
                'descripcion_larga': 'Manejo completo de la cuenta de Instagram de Dogo Armani. Incluye planificacion de contenido, diseno de piezas graficas, redaccion de copys, publicacion y analisis de metricas.',
                'imagen_estatica': 'img/dogo_instagram.jpeg',
                'categoria': 'Redes Sociales',
                'tags': 'Instagram, Community Management, Estrategia, Copywriting',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 9, 1),
                'destacado': False,
                'orden': 6,
            },
            {
                'titulo': 'Gestion de Instagram - Isa Ruiz Arquitectura',
                'slug': 'isa-ruiz-instagram',
                'descripcion': 'Gestion de contenido para el estudio de arquitectura Isa Ruiz: estrategia visual, diseno de posts y crecimiento de la cuenta.',
                'descripcion_larga': 'Creacion y gestion de contenido para @isabelruizarq, estudio de arquitectura y diseno interior en Riobamba. Estrategia visual coherente con la estetica del estudio.',
                'imagen_estatica': 'img/isa_ruiz_instagram.jpeg',
                'categoria': 'Redes Sociales',
                'tags': 'Instagram, Estrategia Visual, Arquitectura, Community Management',
                'cliente': 'Isa Ruiz Arquitectura',
                'fecha': date(2025, 8, 1),
                'destacado': False,
                'orden': 7,
            },
            {
                'titulo': 'Post Instagram - Laboratorio Clinico',
                'slug': 'isa-ruiz-laboratorio',
                'descripcion': 'Diseno de post para Isa Ruiz Arquitectura mostrando el proyecto de un laboratorio clinico. Estetica profesional y elegante.',
                'imagen_estatica': 'img/isa_ruiz_laboratorio.jpeg',
                'categoria': 'Instagram',
                'tags': 'Canva, Diseno de Post, Arquitectura, Redes Sociales',
                'cliente': 'Isa Ruiz Arquitectura',
                'fecha': date(2025, 7, 15),
                'destacado': False,
                'orden': 8,
            },
            {
                'titulo': 'Post Instagram - Servicio a Domicilio',
                'slug': 'dogo-armani-domicilio',
                'descripcion': 'Post promocional de Dogo Armani destacando el servicio a domicilio con numero de contacto directo.',
                'descripcion_larga': 'Pieza grafica para Instagram de Dogo Armani promocionando el servicio a domicilio. Diseno vibrante en la paleta corporativa purpura y amarillo con mascotas protagonistas.',
                'imagen_estatica': 'img/dogo_domicilio.jpeg',
                'categoria': 'Instagram',
                'tags': 'Canva, Diseno de Post, Branding, Redes Sociales',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 11, 1),
                'destacado': False,
                'orden': 9,
            },
            {
                'titulo': 'Peluqueria Canina - Dogo Armani',
                'slug': 'dogo-armani-peluqueria',
                'descripcion': 'Porque sabemos que son los reyes de la casa! En Dogo Armani no solo cortamos el pelo, nos encanta consentirlos!',
                'descripcion_larga': 'Porque sabemos que son los reyes de la casa! En DOGO ARMANI, no solo cortamos el pelo, nos encanta consentirlos! Contamos con el equipo profesional pensado 100% en que tu peludo este comodo y relajado mientras lo dejamos guapisimo. Miren que porte y que seguridad tiene esta pequenita en su sesion de hoy! Le toca bano o corte? Escribenos y reserva su espacio, le va a encantar! 0995666556. Te esperamos en: Avenida Pedro Vicente Maldonado y Antonio Elizalde / Riobamba.',
                'imagen_estatica': 'img/dogo_peluqueria.jpeg',
                'categoria': 'Instagram',
                'tags': 'Fotografia, Peluqueria Canina, Contenido, Redes Sociales',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 10, 15),
                'destacado': False,
                'orden': 10,
            },
            {
                'titulo': 'Reel - Renovacion Licoreria Changuis',
                'slug': 'isa-ruiz-licoreria-changuis',
                'descripcion': 'Reel mostrando la renovacion completa de La Licoreria Changuis por Isa Ruiz Arquitectura. Diseno inspirado en el Chimborazo.',
                'descripcion_larga': 'La Licoreria Changuis ha experimentado un cambio impresionante. En este proyecto de renovacion, el diseno se inspiro en la grandeza del Chimborazo y sus montanas para crear un espacio original. Mediante el uso preciso de colores, texturas y una iluminacion estrategica, se logro transformar completamente el entorno, tanto interior como exterior del local.',
                'imagen_estatica': 'img/reel_licorera.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Arquitectura, Diseno Interior, Instagram, CapCut',
                'cliente': 'Isa Ruiz Arquitectura',
                'fecha': date(2025, 6, 20),
                'destacado': False,
                'url_reel': '',
                'orden': 11,
            },
            {
                'titulo': 'Reel - Studio Decoracion',
                'slug': 'isa-ruiz-studio-decoracion',
                'descripcion': 'Reel mostrando propuestas de decoracion de interiores por Isa Ruiz Arquitectura. Perfecta para cualquier ambiente.',
                'descripcion_larga': 'Perfecta para cualquier ambiente, ya sea tu sala, dormitorio y oficina. Propuestas de decoracion y diseno interior que transforman espacios cotidianos en ambientes unicos y funcionales.',
                'imagen_estatica': 'img/reel_studio.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Decoracion, Diseno Interior, Instagram, CapCut',
                'cliente': 'Isa Ruiz Arquitectura',
                'fecha': date(2025, 5, 15),
                'destacado': False,
                'url_reel': '',
                'orden': 12,
            },
            {
                'titulo': 'Reel - Luz Calida vs Luz Fria',
                'slug': 'isa-ruiz-iluminacion',
                'descripcion': 'Reel sobre iluminacion: diferencias entre luz calida y luz fria para cada ambiente del hogar.',
                'descripcion_larga': 'Prefieres luz calida o luz fria? La luz calida es excelente para generar ambientes acogedores y relajantes, perfecta para espacios de descanso, cuartos y zonas sociales. Por otro lado, la luz fria es perfecta para mejorar la productividad en lugares de trabajo y concentracion como la cocina o el area laboral. Una combinacion de ambas proporciona flexibilidad y se ajusta a diversas necesidades. Busca el equilibrio perfecto en cada zona de tu casa y transformala con la iluminacion adecuada!',
                'imagen_estatica': 'img/presentacion_reel.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Iluminacion, Diseno Interior, Instagram, CapCut',
                'cliente': 'Isa Ruiz Arquitectura',
                'fecha': date(2025, 4, 10),
                'destacado': False,
                'url_reel': '',
                'orden': 13,
            },
            {
                'titulo': 'Reel - Peluqueria Canina Dogo Armani',
                'slug': 'dogo-armani-peluqueria-reel',
                'descripcion': 'Reel promocional de la peluqueria canina de Dogo Armani. Conoce nuestros servicios de cuidado y estilo para mascotas.',
                'descripcion_larga': 'Peluqueria canina: conoce nuestros servicios. Reel mostrando el proceso de cuidado y estilismo para mascotas en Dogo Armani, destacando la calidad y el carino en cada atencion.',
                'imagen_estatica': 'img/reel_petshop.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Peluqueria Canina, Instagram, CapCut',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 10, 5),
                'destacado': False,
                'url_reel': '',
                'orden': 14,
            },
            {
                'titulo': 'Reel - Agenda tu Cita en Dogo Armani',
                'slug': 'dogo-armani-agenda-reel',
                'descripcion': 'Reel para agendar citas en Dogo Armani. Reserva el espacio de tu peludo para bano, corte y estilismo.',
                'descripcion_larga': 'Reel promocional invitando a los clientes a agendar su cita en Dogo Armani. Proceso facil y rapido para reservar el espacio de tu mascota y darle el cuidado que merece.',
                'imagen_estatica': 'img/reel_agenda.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Citas, Peluqueria Canina, Instagram, CapCut',
                'cliente': 'Dogo Armani',
                'fecha': date(2025, 9, 20),
                'destacado': False,
                'url_reel': '',
                'orden': 15,
            },
            {
                'titulo': 'Reel - Mubu Restaurante',
                'slug': 'mubu-restaurante-reel',
                'descripcion': 'Reel promocional para Mubu, restaurante de comida rapida con tradicion. Contenido dinamico para Instagram.',
                'descripcion_larga': 'Reel creado para Mubu, uno de los restaurantes de comida rapida mas antiguos. Contenido audiovisual dinamico para promocionar la marca y sus productos en Instagram.',
                'imagen_estatica': 'img/reel_mubu.mp4',
                'categoria': 'Reel',
                'tags': 'Reel, Restaurante, Comida Rapida, Instagram, CapCut',
                'cliente': 'Mubu Restaurante',
                'fecha': date(2025, 3, 15),
                'destacado': False,
                'url_reel': '',
                'orden': 16,
            },
            {
                'titulo': 'Post Instagram - Mubu Restaurante',
                'slug': 'mubu-restaurante-post',
                'descripcion': 'Post para Mubu Restaurante promocionando alitas y strips de pollo. Fotografia de producto con estetica profesional.',
                'descripcion_larga': 'Tienes ganas de algo super crunch? Pruebas nuestras alitas o strips de pollo estan MUyBUenos. Post disenado para el feed de Instagram de Mubu, restaurante de amigos, picaditas y cafe en Riobamba. Fotografia de producto con enfoque en la textura y presentacion del plato.',
                'imagen_estatica': 'img/mubu_img1.png',
                'imagen_extra_estatica': 'img/mubu_img2.png',
                'categoria': 'Instagram',
                'tags': 'Fotografia, Restaurante, Comida, Redes Sociales',
                'cliente': 'Mubu Restaurante',
                'fecha': date(2025, 3, 10),
                'destacado': False,
                'orden': 17,
            },
            {
                'titulo': 'Gestion de Instagram - Mubu Restaurante',
                'slug': 'mubu-restaurante-instagram',
                'descripcion': 'Gestion integral del perfil de Instagram @mu_.bu: estrategia de contenido, fotografia de producto, copywriting y crecimiento organico.',
                'descripcion_larga': 'Manejo completo de la cuenta de Instagram de Mubu, restaurante de amigos, picaditas y cafe en Riobamba. Incluye planificacion de contenido, fotografia de producto, diseno de piezas graficas, redaccion de copys, promociones y analisis de metricas. Av. Pedro Vicente Maldonado y Antonio Elizalde, Riobamba.',
                'imagen_estatica': 'img/mubu_instagram.png',
                'categoria': 'Redes Sociales',
                'tags': 'Instagram, Community Management, Fotografia, Restaurante',
                'cliente': 'Mubu Restaurante',
                'fecha': date(2025, 3, 1),
                'destacado': False,
                'orden': 18,
            },
            {
                'titulo': 'Post Instagram - Alitas Mubu',
                'slug': 'mubu-restaurante-alitas',
                'descripcion': 'Fotografia de producto para Mubu Restaurante. Alitas crocantes con salsa verde, imagen profesional para el feed de Instagram.',
                'descripcion_larga': 'Fotografia profesional de producto para el feed de Instagram de Mubu. Alitas crocantes acompanadas de salsa verde y papas fritas. Imagen disenada para generar apetito y engagement en redes sociales.',
                'imagen_estatica': 'img/mubu_img3.png',
                'imagen_extra_estatica': 'img/mubu_img4.png',
                'categoria': 'Instagram',
                'tags': 'Fotografia, Restaurante, Comida, Redes Sociales',
                'cliente': 'Mubu Restaurante',
                'fecha': date(2025, 2, 20),
                'destacado': False,
                'orden': 19,
            },
        ]
        for p in proyectos:
            Proyecto.objects.update_or_create(slug=p['slug'], defaults=p)
        self.stdout.write(self.style.SUCCESS(f'{len(proyectos)} proyectos cargados'))
