# Generated by Django 6.0.3 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
                "ordering": ["categoria", "orden"],
            },
        ),
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("empresa", models.CharField(blank=True, max_length=100)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                ("descripcion_larga", models.TextField(blank=True)),
                ("imagen", models.ImageField(upload_to="proyectos/")),
                (
                    "imagen_extra",
                    models.ImageField(blank=True, null=True, upload_to="proyectos/"),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=300)),
                ("cliente", models.CharField(default="Dogo Armani", max_length=100)),
                ("fecha", models.DateField()),
                ("destacado", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["orden", "-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                ("icono", models.CharField(max_length=10)),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["orden"],
            },
        ),
    ]
