# Generated by Django 6.0.3 on 2026-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="imagen_estatica",
            field=models.CharField(
                blank=True,
                help_text="Ruta relativa en static/img/, ej: img/dogo_post.jpg",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="imagen_extra_estatica",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="url_reel",
            field=models.URLField(
                blank=True, help_text="URL del Reel de Instagram (opcional)"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="proyectos/"),
        ),
    ]
